pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Cehiim/ProjectTemis.git'
            }
        }
        stage('Build') {
            steps {
                dir('/var/lib/jenkins/workspace/Pipeline Projeto/Front-end') {
                    sh 'pwd'
                    sh 'npm install'
                    }
                }
            }
        
        stage('Test') {
            steps {
                    dir('/var/lib/jenkins/workspace/Pipeline Projeto/Front-end/jenkins/scripts') {
                    sh './test.sh'
                    }
            }
        }
        stage('Deliver') { 
            steps {
                sh './deliver.sh' 
                input message: 'Finished using the web site? (Click "Proceed" to continue)' 
                sh './kill.sh' 
            }
        }
    }
}