pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Cehiim/ProjectTemis.git'
            }
        }
        stage('Build') {
            steps {
                dir('/var/lib/jenkins/workspace/Pipeline Projeto/Front-end') {
                    sh 'npm install @testing-library/jest-dom @testing-library/react @testing-library/user-event -D'
                    }
                }
            }
        
        stage('Test') {
            steps {
                    dir('/var/lib/jenkins/workspace/Pipeline Projeto/Front-end/jenkins/scripts') {
                    sh './test.sh'
                    }
            }
        }
        stage('Deliver') { 
            steps {
                dir('/var/lib/jenkins/workspace/Pipeline Projeto/Front-end/jenkins/scripts') {
                    sh './deliver.sh'
                    
                    //Lembrar de clicar em Proceed pra matar o processo
                    input message: 'Finished using the web site? (Click "Proceed" to continue)' 
                    sh './kill.sh'
                    }
            }
        }
    }
}